Repository url2ref/url2ref, pull requests merged in 2023-12, with the labels that each got.

#1 Created workflow config
  .github/workflows/build_and_test.yml
  npm/build.sh
  npm/package.json
Labels: meta

#3 Give compiled binaries more meaningful names
  .github/workflows/build_and_test.yml
  Cargo.toml
  npm/build.sh
  npm/package.json
Labels: build process

#5 Improve README
  CONTRIBUTING.md
  README.md
Labels: meta

#2 Base structure for backend
  CONTRIBUTING.md
  Cargo.toml
  README.md
  src/attribute.rs
  src/bin/cli/main.rs
  src/bin/web/main.rs
  src/bin/web/scss.rs
  src/generator.rs
  src/lib.rs
  src/opengraph.rs
  src/parser.rs
  src/reference.rs
  src/schema_org.rs
  tests/.gitkeep
  tests/test.rs
Labels: enhancement, build process

#13 Implement SchemaOrg parsing
  Cargo.toml
  src/opengraph.rs
  src/parser.rs
  src/schema_org.rs
  src/schema_org/author.rs
  src/schema_org/generic.rs
  src/schema_org/site.rs
Labels: enhancement, lib

#14 Add more thorough testing
  Cargo.toml
  src/attribute.rs
  src/generator.rs
  src/lib.rs
  src/opengraph.rs
  src/parser.rs
  src/reference.rs
  tests/.gitkeep
  tests/data/case1/expected.yml
  tests/data/case1/politiken_dk_2023-12-11.html
  tests/data/case2/expected.yml
  tests/data/case2/jyllands-posten_dk_2023-12-13.html
  tests/data/case3/dr_dk_2023-12-13.html
  tests/data/case3/expected.yml
  tests/data/case4/expected.yml
  tests/data/case4/information_dk_2023-12-13.html
  tests/data/case5/expected.yml
  tests/data/case5/information_dk_2023-12-13.html
  tests/data/case6/expected.yml
  tests/data/case6/wsj_com_2023-12-12.html
  tests/data/case7/expected.yml
  tests/data/case7/the-sun_co-uk_2023-12-14.html
  tests/test.rs
  tests/test_suite.rs
Labels: tests, lib

#18 v0.2.0
  .github/workflows/build_and_test.yml
  Cargo.toml
  README.md
  src/attribute.rs
  src/bin/cli/main.rs
  src/citation.rs
  src/generator.rs
  src/lib.rs
  src/opengraph.rs
  src/parser.rs
  src/reference.rs
  src/schema_org.rs
  src/schema_org/author.rs
  src/schema_org/generic.rs
  src/schema_org/site.rs
  tests/.gitkeep
  tests/data/case1/expected.yml
  tests/data/case1/politiken_dk_2023-12-11.html
  tests/data/case2/expected.yml
  tests/data/case2/jyllands-posten_dk_2023-12-13.html
  tests/data/case3/dr_dk_2023-12-13.html
  tests/data/case3/expected.yml
  tests/data/case4/expected.yml
  tests/data/case4/information_dk_2023-12-13.html
  tests/data/case5/expected.yml
  tests/data/case5/information_dk_2023-12-13.html
  tests/data/case6/expected.yml
  tests/data/case6/wsj_com_2023-12-12.html
  tests/data/case7/expected.yml
  tests/data/case7/the-sun_co-uk_2023-12-14.html
  tests/test.rs
  tests/test_priority.rs
  tests/test_suite.rs
  tests/utils/mod.rs
Labels: version update
