Repository url2ref/url2ref, pull requests merged in 2024-03, with the labels that each got.

#23 Backend improvements
  url2ref/Cargo.toml
  url2ref/src/curl.rs
  url2ref/src/doi.rs
  url2ref/src/generator.rs
  url2ref/src/lib.rs
  url2ref/src/opengraph.rs
  url2ref/src/parser.rs
  url2ref/src/schema_org.rs
  url2ref/tests/data/case1/expected.yml
  url2ref/tests/data/case4/expected.yml
  url2ref/tests/data/case4/information_dk_2023-12-13.html
  url2ref/tests/data/case5/expected.yml
  url2ref/tests/data/case5/information_dk_2023-12-13.html
  url2ref/tests/test_suite.rs
Labels: enhancement, lib

#26 Add dependabot support
  .github/dependabot.yml
Labels: meta

#25 Implementing support for archive URL and date
  url2ref-cli/src/main.rs
  url2ref/src/attribute.rs
  url2ref/src/citation.rs
  url2ref/src/doi.rs
  url2ref/src/generator.rs
  url2ref/src/lib.rs
  url2ref/src/parser.rs
  url2ref/src/reference.rs
  url2ref/tests/utils/mod.rs
Labels: enhancement, lib

#34 Respect ArchiveOptions
  url2ref/src/generator.rs
Labels: bug, lib

#36 Add support for Docker containers
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: meta
